name: Build, Package & Publish VS Code Extension

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Read version
        id: meta
        run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Package (.vsix)
        run: pnpm run package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: chronoshade-${{ env.VERSION }}.vsix
          path: chronoshade-${{ env.VERSION }}.vsix

      # --- Publish ONLY when a tag like v1.2.3 is pushed ---
      - name: Publish to VS Marketplace
        if: startsWith(github.ref, 'refs/tags/')
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: pnpm dlx @vscode/vsce publish --packagePath chronoshade-${{ env.VERSION }}.vsix
